SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SPEED = 200

SHOT_RADIUS = 5

PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.25

# Alien ship constants
ALIEN_RADIUS = 15
ALIEN_SPEED = 100
ALIEN_SHOOT_COOLDOWN = 1.5  # seconds
ALIEN_SHOOT_SPEED = 300
ALIEN_SPAWN_SCORE = 25  # Score threshold to spawn alien